pipeline {
  agent any
  options {
    disableConcurrentBuilds()
  }
  environment {
    DOCKER_TLS_VERIFY = '1'
    DOCKER_HOST = "${MINIKUBE_TCP}"
    DOCKER_CERT_PATH = '/var/jenkins_home/minikube/certs'
  }
  stages {
    stage('Checkout') {
      steps {
        sh "docker images"
      }
    }
  }
}