pipeline {
    agent any
    triggers {
        pollSCM('* * * * *')
    }
    stages {
        stage('Checkout') {
            steps {
                sh 'echo "hello 1"'
            }
            post {
                always {
                    sh 'echo "Test post"'
                    // sh 'docker rm -f httpd'
                }
            }
        }
    }
}