pipeline {
  agent any
//  parameters {
//    string(name: 'SERVICE', defaultValue: 'oc-shopping-list')
//    string(name: 'ENVIRONMENT', defaultValue: 'develop')
//    string(name: 'BRANCH', defaultValue: 'omni-channel-phase1')
//  }
  environment {
    SERVICE = 'oc-shopping-list'
    ENVIRONMENT = 'develop'
    BRANCH = 'omni-channel-phase1'
  }
  options {
    disableConcurrentBuilds()
  }
  triggers {
    pollSCM('* * * * *')
  }
  stages {
    stage('Checkout') {
      steps {
        checkout([
          $class: 'SubversionSCM',
          additionalCredentials: [],
          excludedCommitMessages: '',
          excludedRegions: '',
          excludedRevprop: '',
          excludedUsers: '',
          filterChangelog: false,
          ignoreDirPropChanges: false,
          includedRegions: '',
          locations: [
            [
              remote: "https://svn.chowsangsang.com/repos/uat/oc_storefront/microservice/${env.SERVICE}/${env.ENVIRONMENT}/${env.BRANCH}",
              cancelProcessOnExternalsFail: true,
              credentialsId: 'css_svn',
              depthOption: 'infinity',
              ignoreExternalsOption: true,
              local: 'microservice/${SERVICE}'
            ]
          ]
        ])
      }
    }
    stage('Integration Test') {
      steps {
        sh "docker rm -f eshop_json_server || true"
        sh "docker create --name eshop_json_server -p 36880:80 clue/json-server"
        sh "sleep 10"
        dir("microservice/${SERVICE}/integration-test/json-server-data/") {
          sh "docker cp 'db.json' 'eshop_json_server:/data/db.json'"
          sh "docker cp 'json-server.json' 'eshop_json_server:/data/json-server.json'"
          sh "docker cp 'middleware-1.js' 'eshop_json_server:/data/middleware-1.js'"
          sh "docker cp 'routes.json' 'eshop_json_server:/data/routes.json'"
        }
        sh "docker start eshop_json_server"
      }
    }
  }
}